### ISSUE TITLE
marching_cubes_cpp import error

### ISSUE THREAD

**Issue by Z-Jeff** [angeladai/sgnn#10]
I have run `sudo python2 setup.py install` under `torch/marching_cubes/` to install marching_cubes.
Then, I run `python2 test_scene.py --gpu 0 --input_data_path ./data/mp_sdf_vox_2cm_input.zip --target_data_path ./data/mp_sdf_vox_2cm_target.zip --test_file_list ../filelists/mp-rooms_val-scenes.txt --model_path sgnn.pth --output --max_to_vis 20`, error occurs:
```
Traceback (most recent call last):
  File "test_scene.py", line 11, in <module>
    import data_util
  File "/home/user01/ZhengJiafang/sgnn/torch/data_util.py", line 9, in <module>
    import marching_cubes.marching_cubes as mc
  File "/home/user01/ZhengJiafang/sgnn/torch/marching_cubes/marching_cubes.py", line 6, in <module>
    import marching_cubes_cpp
  File "build/bdist.linux-x86_64/egg/marching_cubes_cpp.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/marching_cubes_cpp.py", line 6, in __bootstrap__
ImportError: /home/user01/.cache/Python-Eggs/marching_cubes_cpp-0.0.0-py2.7-linux-x86_64.egg-tmp/marching_cubes_cpp.so: undefined symbol: _ZN6caffe26detail36_typeMetaDataInstance_preallocated_7E
```
How can I fix this?

**Comment by xxyLA** [comment]
hey could you provide a lite version data of those three zips like only including one room just for test? Thanks a lot!
